### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rabeaasdss** [DumbDannyLol/TokenGen#1]
got error while filling the informations of  registering

**Comment by DumbDannyLol** [comment]
Can i see the error? DM me on discord @DumbDanny#0001. I will fix it within an hour.

**Comment by rabeaasdss** [comment]
friend added

**Comment by DumbDannyLol** [comment]
Could you give me your discord? There are hundreds of people adding me, so ill add you.

**Comment by Overpowerdgamr101** [comment]
can u add me on discord i need help with smthToxice#5984

**Comment by DumbDannyLol** [comment]
@Overpowerdgamr101 It showed up as an invalid @. Please make sure you sent me the correct user, and I will add you ASAP.

**Comment by Overpowerdgamr** [comment]
Toxice#5984

**Comment by DumbDannyLol** [comment]
What up @Overpowerdgamr

**Comment by DumbDannyLol** [comment]
I added you
